name: 'mud'
version: 0.0.1
description: An absolute bare-bones web app.
#author: Jose Segovia <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
#  my_dependency: any
  unittest:
  rpc: '^0.5.5'
  http: '>=0.11.1 <0.12.0'
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  mongo_dart: '^0.2.4'


dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  test: "0.12.16"

transformers:
- dart_to_js_script_rewriter
